### ISSUE TITLE
My app does not compile after adding the package to my Xcode project.

### ISSUE THREAD

**Issue by yuksekyusuf** [EmergeTools/Pow#46]
It gives the following error inside the AngleControl struct:

![tempImageVtpRVm](https://github.com/EmergeTools/Pow/assets/68251921/b06fb70d-7640-4181-a618-207a91140a62)

**Comment by mergesort** [comment]
This has been fixed thanks to @Itaybre, and is now available in [version 1.0.2](https://github.com/EmergeTools/Pow/releases/tag/1.0.2).

**Comment by yuksekyusuf** [comment]
Greatly appreciate it!
