### ISSUE TITLE
Use in UIKit

### ISSUE THREAD

**Issue by anaclumos** [EmergeTools/Pow#58]
It is possible to use this library in UIKit?

**Comment by mergesort** [comment]
Hi @anaclumos! While Pow does not provide any direct APIs for use in UIKit if you would like to use Pow in a UIKit project you can use the same APIs you would use to embed a SwiftUI View in your UIKit app, most notably [`UIHostingController`](https://developer.apple.com/documentation/swiftui/uihostingcontroller) or [`UIHostingConfiguration`](https://developer.apple.com/documentation/SwiftUI/UIHostingConfiguration).
