### ISSUE TITLE
When HStack appears, there is no spring animation, which feels a bit abrupt.

### ISSUE THREAD

**Issue by zhu-hongwei** [EmergeTools/Pow#59]
https://movingparts.io/pow#move

**Comment by zhu-hongwei** [comment]
```swift
import SwiftUI
import Pow

struct TestUI: View {
  @State var isAdded = false

  var body: some View {
    ZStack {
      Color.clear

      if isAdded {
        Image("zb_yezi")
          .resizable()
          .frame(width: 150, height: 200)
          .transition(
            .asymmetric(
                insertion: .movingParts.move(
                  angle: .degrees(-45)
                ),
                removal: .movingParts.move(
                  angle: .degrees(135)
                )
            ).combined(with: .opacity)
          )
      }
    }
    .contentShape(Rectangle())
    .onTapGesture {
      withAnimation {
        isAdded.toggle()
      }
    }
  }
}

```

**Comment by zhu-hongwei** [comment]
https://github.com/EmergeTools/Pow/assets/61079864/15085772-909c-4509-80c0-6f90fcffc71d

**Comment by zhu-hongwei** [comment]
It feels like a lot of the detailed effects showcased on the web don't translate to real device performance. Unfortunately, my SwiftUI skills are still quite weak.

**Comment by mergesort** [comment]
Hey @zhu-hongwei, the effects showcased on the web are animations that were recorded on a real device so they should translate your iOS app. The code on the website is meant to demonstrate how the transitions work, but what the code you posted is missing is an animation to give it the springiness you're looking for.

If you want additional bounciness you'll want to add something like this to the `ZStack`, or you can substitute whatever animation you find suitable for your app's look and feel. 
```swift
ZStack {
    // All the other code stays the same
}
.animation(.spring(response: 0.25, dampingFraction: 0.5), value: isAdded)
```

Hope that answers your question and gives you a good starting point for your app!
