### ISSUE TITLE
Haptics stop work when switch App

### ISSUE THREAD

**Issue by dimabiserov** [EmergeTools/Pow#69]
Hi! when I switch to another app and back to my app, the vibrations stop working, especially the spray effect

**Comment by kkiermasz** [comment]
I'm experiencing the same issue. 
Adding to that, no errors in the console regarding haptics engine.

**Comment by dimabiserov** [comment]
> I'm experiencing the same issue. Additionally, there are no errors in the console regarding the haptics engine by default.
> 
> 
> 
> I tried to investigate this issue a bit and noticed that the call to `CHHapticEngine` inside the `Haptics.play(_:at:)` method ignores thrown errors. I modified this, and can confirm that after the app becomes foreground again, the following error is thrown:
> 
> 
> 
> ```
> 
> (lldb) po error
> 
> Error Domain=com.apple.CoreHaptics Code=-4805 "(null)" UserInfo={Error =self.running}
> 
> (lldb) po error.localizedDescription
> 
> "The operation couldn’t be completed. (com.apple.CoreHaptics error -4805.)"
> 
> ```
> 
> 
> 
> Any ideas, folks? I'm happy to open a PR with a fix, but I have no idea what causes this.
> 
> 
> 
> 
> 
> Edit:
> 
> I fixed it, in the #70. @dimabiserov you can use my fork till it's merged :) 

thanks a lot!
Maybe you can also make it so that the sounds from pow (they are cool there) play in silent mode?
No matter what I did, it didn't wor

**Comment by kkiermasz** [comment]
Let's mark it as resolved @mergesort

**Comment by mergesort** [comment]
Fixed in #70, thank you @kkiermasz!
